import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.scss"

import SideNav from "../components/nav/SideNav"
import Body from "../components/home/Body"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BoBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SideNav/>
        <Body />
      </main>
    </div>
  );
}
